name: pixelated_shimmer
description: A Dart package providing utilities or widgets for pixelated shimmer effects.
version: 0.0.1
repository: https://github.com/louislamlam/pixelated_shimmer

environment:
  sdk: ^3.5.0

dependencies:
  image: ^4.5.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
